#!/bin/bash

sudo apt install proftpd-*
sudo apt install openssl
echo -e "\e[0;36m le paquet ProFTPd a été\e[0m \e [0;31m installé \e[0m"

sudo groupadd ftpgroup
cd /etc/proftpd
sudo mkdir ssl

sudo cat /home/yassi/job7/conf.proftpd > /etc/proftpd/proftpd.conf
sudo cat /home/yassi/job7/conf.tls > /etc/proftpd/tls.conf
sudo cat /home/yassi/job7/conf.modules > /etc/proftpd/modules.conf
echo -e "\e [0;36m Les configurations ont été \e[0m \e[0;31m modifié \e[0m"

sudo openssl req -new -x509 -xkeyout /etc/proftpd/ssl/proftpd.key.pem -days 365 -nodes -out
echo -e "\e[0;36m La clef et le certificat ont été \e[0;31m généré \e[0m"
